### ISSUE TITLE
Integrate Substrate playground into our tutorials

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#425] opened 2020-01-20 15:08 UTC
- I (Jimmy) will try to integrate playground in off-chain worker tutorial and see how hard this process is

**Comment by JoshOrndorff** [comment] 2020-01-20 15:13
cc @jeluard

**Comment by jeluard** [comment] 2020-01-20 15:46
Can you (Jimmy) detail what you have in mind?

**Comment by JoshOrndorff** [comment] 2020-03-16 16:20
Dupe of 426, now moved to https://github.com/paritytech/substrate.io/issues/1

**Closed by JoshOrndorff** 2020-03-16 16:20 UTC
